{{- if .Values.install.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-ingress 
  namespace: {{ .Release.Namespace }}
  annotations:
    acme.cert-manager.io/http01-edit-in-place: 'true'  
    cert-manager.io/issuer: {{ .Release.Name }}-issuer
    kubernetes.io/ingress.class: nginx  
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.url }}
    secretName: {{ .Release.Name }}-tls  
  rules:
  - host: {{ .Release.Name }}.{{ .Values.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
{{- end }}